[Source](https://github.com/greyhatguy007/Mathematics-for-Machine-Learning-and-Data-Science-Specialization-Coursera)


##**Basics of NumPy**

NumPy (Numerical Python) is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency. In this lab you will learn several key NumPy functions, such as creating numpy arrays, slicing, indexing, reshaping and stacking.

Arrays are one of the core data structures of the NumPy library, essential for organizing your data.

NumPy provides an array object that is much faster and more compact than Python lists.

Numpy array storing elements of the same data types.

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'.

### Packages

You have to import NumPy to load its functions.


In [ ]:
# pip install numpy

In [15]:
# Importing NumPy
import numpy as np

### Creating NumPy Arrays

There are several ways to create an array in NumPy. You can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument and returns a 1-D array.



In [16]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval.

In [17]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [18]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


To change the type to integers, you need to set the dtype to `int`.

In [19]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [20]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


### More on NumPy arrays ###

One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:
- `np.ones()` - Returns a new array setting values to one.
- `np.zeros()` - Returns a new array setting values to zero.
- `np.empty()` - Returns a new uninitialized array.
- `np.random.rand()` - Returns a new array with values chosen at random.


In [21]:
# Return a new array of shape 3, filled with ones.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [22]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [23]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [56]:

# Generate a random integer from 0 to 100:
x = np.random.randint(100)

print(x)


42


In [57]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.96630068 0.15041174 0.29899444]


In [60]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

x=np.random.randint(100, size=(5))

print(x)


[90 13 64 25  8]


#**Multidimensional Arrays**
With NumPy you can also create arrays with more than one dimension. In the above examples, you dealt with 1-D arrays, where you can access their elements using a single index. A multidimensional array has more than one column.

In [25]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional array is by reshaping the initial 1-D array. Using `np.reshape()`. you can rearrange elements of the previous array into a new shape.

In [26]:
# 1-D array
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (2,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


### Finding size, shape and dimension. ##

- `ndarray.ndim` - Stores the number dimensions of the array.
- `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
- `ndarray.size` - Stores the number of elements in the array.


In [27]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [28]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [29]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

### Array math operations #


In [30]:
# Adding two 1-D arrays

arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

addition = arr_1 + arr_2
print(addition)

[ 3  7 11]


In [31]:
# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

[1 1 1]


In [32]:
# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 2 12 30]


In [33]:
# Multiplying array with a scalar
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

### Indexing ##

Numpy array indexing starts with 0, meaning that the first element has index 0, and the second has index 1 etc.



In [34]:
# Select the third element of the array. Remember the counting starts from 0.
a = np.array([1, 2, 3, 4, 5])

print(a[2])

3


In [35]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


### Slicing ###
The syntax is:

`array[start:end:step]`

If no value is passed to start, it is assumed `start = 0`, if no value is passed to end, it is assumed that `end = length of array - 1` and if no value is passed to step, it is assumed `step = 1`.

In [36]:
a = np.array([1, 2, 3, 4, 5])

In [37]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [38]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1 2 3]


In [39]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [40]:
# Slice the two_dim array to get the first two rows
two_dim = np.array(([1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]))

sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [42]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


###  Stacking ###
- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays


In [43]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [44]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [45]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


##`numpy.sum()`




In [46]:
array1 = np.array(
    [[1, 2],
     [3, 4],
     [5, 6]])

#Sum of All the Elements in the Array
total = np.sum(array1)
print(total)

21


In [50]:
#Sum of Array Elements Along the Axis
total_0_axis = np.sum(array1, axis=0)

print(total_0_axis)

[ 9 12]


In [51]:
total_1_axis = np.sum(array1, axis=1)
print(total_1_axis)

[ 3  7 11]


# **Exercises:**

# **Question:**

You are given a 1D NumPy array of integers. Write a Python function that performs the following operations:

1. **Reshape** the 1D array into a 2D array with **3 rows**. If the number of elements in the array is not divisible by 3, trim the excess elements from the end so that the reshaping is possible.
2. **Compute the total sum** of all elements in the resulting 2D array.
3. **Compute the sum of each row** and append these sums as a new column to the 2D array.
4. **Return** **the** final 2D array with the row sums appended as an additional column.

### *Example:*

Given the input array:

$\text{arr} = \begin{bmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \end{bmatrix}$





###**More useful array operations**

1. Reverse a numpy array
2. Sorting an numpy array
3. Array Division
4. Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100.
5. Numpy array multiplication.
6.Using `np.hsplit()` - splits an array into several smaller arrays

7. Using numpy compute mean, median, mode, quartiles, standard deviation, and variance based on axis.