Q1

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr = arr**3
print(arr)

[  1   8  27  64 125]


Q2

In [54]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
i = int(input("enter value of i: "))
j = int(input("enter value of j: "))
arr[:,[i,j]] = arr[:,[j,i]]
arr

enter value of i: 0
enter value of j: 2


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

Q3

In [59]:
import numpy as np
arr = np.array([[10,25,17],[22,13,30],[5,45,20]])
threshold = 20
indices = np.where(arr > 20)
print(indices)


(array([0, 1, 1, 2]), array([1, 0, 2, 1]))


Q4

In [64]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90])
sample = np.random.choice(arr,size = 4)
sample

array([80, 70, 50, 70])

Q5

In [65]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
dist = np.linalg.norm(a - b)
print(dist)

5.196152422706632


Q6

In [66]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar = 5
arr = arr+5
print(arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Q7

In [67]:
import numpy as np
A = np.array([[2,1],[1,3]])
B = np.array([5,7])
arr =  np.linalg.solve(A, B)
print(arr)

[1.6 1.8]


Q8

In [76]:
import numpy as np
for i in range(25):
  blood_pressure = np.random.randint(100,200,size=4)
  mean = np.mean(blood_pressure)
  print(mean,end=" ")


158.75 141.5 141.25 139.25 141.0 146.5 145.0 135.75 167.75 131.0 169.25 153.25 176.25 153.5 141.25 125.0 153.0 159.25 158.0 142.0 139.75 156.25 158.75 156.5 132.0 

Q9

In [79]:
import numpy as np
arr = np.random.randint(0,50,size=(3,4,5))
arr[1]

array([[41,  2, 24, 22, 24],
       [26, 31, 14, 21,  9],
       [32, 24, 36, 23, 17],
       [16,  3, 12,  0, 31]])

Q10

In [87]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
arr = np.add.outer(a,b)
arr2 = np.multiply.outer(a,b)
print(arr)
print(arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Q11

In [91]:
import numpy as np
arr = np.array([3,4,5])
mag = np.linalg.norm(arr)
print(mag)

7.0710678118654755


Q12

In [94]:
import numpy as np
arr = np.array([1,2,3])
arr2 = np.array([4,5,6])
v_norm = np.sqrt(sum(arr2**2))
proj_of_u_on_v = (np.dot(arr, arr2)/v_norm**2)*arr2
print(proj_of_u_on_v)

[1.66233766 2.07792208 2.49350649]
